# Generated by Django 5.1.5 on 2025-01-29 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('income_group', models.CharField(choices=[('0-$25K', '0-$25K'), ('$25-$70K', '$25-$70K'), ('>$70K', '>$70K')], max_length=20)),
                ('region', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=20)),
                ('marital_status', models.BooleanField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateTimeField()),
                ('fuel', models.CharField(choices=[('CNG', 'CNG'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol')], max_length=10)),
                ('vehicle_segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bodily_injury_liability', models.BooleanField()),
                ('personal_injury_protection', models.BooleanField()),
                ('property_damage_liability', models.BooleanField()),
                ('collision', models.BooleanField()),
                ('comprehensive', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='analysis.customer')),
            ],
            options={
                'db_table': 'policy',
            },
        ),
    ]
