services:
  postgres:
    image: postgres
    container_name: database-container
    environment:
      POSTGRES_PASSWORD: blablabla
      POSTGRES_USER: blablabla
      POSTGRES_DB: DataSetInsuranceClient
    ports:
      - "5433:5432"
    restart: unless-stopped

  data-importer:
    image: drisschammi10/data-importer:v1
    container_name: data-importer-container
    depends_on:
      - postgres
    env_file:
      - ./.env
    restart: "no"

  django-app:
    image: drisschammi10/django-data-analysis:v1
    container_name: django-container
    depends_on:
      - data-importer
    env_file:
      - ./.env
    ports:
      - "8000:8000"